name: Build LaTeX

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Move pdf
        run: |
          mkdir -p ./output
          mv main.pdf ./output/setTheory.pdf

      - name: Publish to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages